### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by RuthSalvador** [BuscoANemo/LIM011-data-lovers#2]
Objetivos pendientes:

- Diseñar la aplicación pensando y entendiendo al usuario. 
- Aplicar los principios de diseño visual (contraste, alineación, jerarquía). 
- Planear y ejecutar tests de usabilidad.
- Entender y reconocer por qué es importante el HTML semántico
- Entender como funciona flexbox en CSS. 
- Construir tu aplicación respetando el diseño realizado (maquetación).
- Manejo de eventos del DOM. (addEventListener)
- Manipulación dinámica del DOM.(createElement, appendchild, innerHTML, value)
- Entender la diferencia entre expression y statements. ([LMS](https://lms.laboratoria.la/cohorts/lim-2019-09-bc-core-lim011/courses/javascript/03-functions/01-classic))
- Entender la diferencia entre tipos de datos atómicos y estructurados.
- Colaborar en Github (pull requests).

Planificarse en base a sus OA, los desglosará con el fin de enfocarse a mayor detalle en ellos.

**Comment by yamiroot** [comment]
Gracias Ruth
